# Generated from protos/example.proto
# DO NOT EDIT: This file is automatically generated by protoc-gen-py-mcp
# Plugin version: protoc-gen-py-mcp

from typing import Optional, List, Dict, Any
from fastmcp import FastMCP
from google.protobuf import json_format

import protos.example_pb2

def create_vibeservice_server() -> FastMCP:
    """Create an MCP server for VibeService service tools."""
    mcp = FastMCP("VibeService")

    @mcp.tool()
    def set_vibe(vibe: str) -> dict:
        """Tool for SetVibe RPC method."""
        # Parameters:
        #   vibe: str
        
        # Construct request message
        request = protos.example_pb2.SetVibeRequest()
        request.vibe = vibe
        
        # TODO: Implement actual SetVibe logic here
        # For now, create an empty response
        response = protos.example_pb2.SetVibeResponse()
        
        # Convert response to dict for MCP
        result = json_format.MessageToDict(response, use_integers_for_enums=True)
        return result
    
    @mcp.tool()
    def get_vibe() -> dict:
        """Tool for GetVibe RPC method."""
        # Construct request message
        request = protos.example_pb2.GetVibeRequest()
        
        # TODO: Implement actual GetVibe logic here
        # For now, create an empty response
        response = protos.example_pb2.GetVibeResponse()
        
        # Convert response to dict for MCP
        result = json_format.MessageToDict(response, use_integers_for_enums=True)
        return result
    
    return mcp

