# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import example_pb2 as protos_dot_example__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/example_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VibeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetVibe = channel.unary_unary(
                '/examples.v1.VibeService/SetVibe',
                request_serializer=protos_dot_example__pb2.SetVibeRequest.SerializeToString,
                response_deserializer=protos_dot_example__pb2.SetVibeResponse.FromString,
                _registered_method=True)
        self.GetVibe = channel.unary_unary(
                '/examples.v1.VibeService/GetVibe',
                request_serializer=protos_dot_example__pb2.GetVibeRequest.SerializeToString,
                response_deserializer=protos_dot_example__pb2.GetVibeResponse.FromString,
                _registered_method=True)


class VibeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetVibe(self, request, context):
        """Set the Vibe
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVibe(self, request, context):
        """Get Vibe
        of the server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VibeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetVibe': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVibe,
                    request_deserializer=protos_dot_example__pb2.SetVibeRequest.FromString,
                    response_serializer=protos_dot_example__pb2.SetVibeResponse.SerializeToString,
            ),
            'GetVibe': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVibe,
                    request_deserializer=protos_dot_example__pb2.GetVibeRequest.FromString,
                    response_serializer=protos_dot_example__pb2.GetVibeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'examples.v1.VibeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('examples.v1.VibeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VibeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetVibe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/examples.v1.VibeService/SetVibe',
            protos_dot_example__pb2.SetVibeRequest.SerializeToString,
            protos_dot_example__pb2.SetVibeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVibe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/examples.v1.VibeService/GetVibe',
            protos_dot_example__pb2.GetVibeRequest.SerializeToString,
            protos_dot_example__pb2.GetVibeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
