# Generated from protos/example.proto
# DO NOT EDIT: This file is automatically generated by protoc-gen-py-mcp
# Plugin version: protoc-gen-py-mcp

from typing import Optional, List, Dict, Any
from fastmcp import FastMCP
from google.protobuf import json_format
import grpc

import protos.example_pb2
import protos.example_pb2_grpc

mcp = FastMCP("MCP Server from Proto")

@mcp.tool(name="SetVibe", description="Set the Vibe")
def set_vibe(vibe: str):
    """Tool for SetVibe RPC method.
    
    Set the Vibe
    """
    # Construct request message
    request = protos.example_pb2.SetVibeRequest()
    request.vibe = vibe
    
    channel = grpc.insecure_channel('localhost:50051')
    stub = protos.example_pb2_grpc.VibeServiceStub(channel)
    response = stub.SetVibe(request)
    print(response)

@mcp.tool(name="GetVibe", description="Get Vibe  of the server")
def get_vibe():
    """Tool for GetVibe RPC method.
    
    Get Vibe
 of the server
    """
    # Construct request message
    request = protos.example_pb2.GetVibeRequest()
    
    channel = grpc.insecure_channel('localhost:50051')
    stub = protos.example_pb2_grpc.VibeServiceStub(channel)
    response = stub.GetVibe(request)
    print(response)


if __name__ == '__main__':
    mcp.run()

