# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/example.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/example.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/example.proto\x12\x0b\x65xamples.v1\"\x1e\n\x0eSetVibeRequest\x12\x0c\n\x04vibe\x18\x01 \x01(\t\"6\n\x0fSetVibeResponse\x12\x15\n\rprevious_vibe\x18\x01 \x01(\t\x12\x0c\n\x04vibe\x18\x02 \x01(\t\"\x10\n\x0eGetVibeRequest\"\x1f\n\x0fGetVibeResponse\x12\x0c\n\x04vibe\x18\x01 \x01(\t2\x9d\x01\n\x0bVibeService\x12\x46\n\x07SetVibe\x12\x1b.examples.v1.SetVibeRequest\x1a\x1c.examples.v1.SetVibeResponse\"\x00\x12\x46\n\x07GetVibe\x12\x1b.examples.v1.GetVibeRequest\x1a\x1c.examples.v1.GetVibeResponse\"\x00\x42#Z!examples/gen/example/v1;examplev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z!examples/gen/example/v1;examplev1'
  _globals['_SETVIBEREQUEST']._serialized_start=37
  _globals['_SETVIBEREQUEST']._serialized_end=67
  _globals['_SETVIBERESPONSE']._serialized_start=69
  _globals['_SETVIBERESPONSE']._serialized_end=123
  _globals['_GETVIBEREQUEST']._serialized_start=125
  _globals['_GETVIBEREQUEST']._serialized_end=141
  _globals['_GETVIBERESPONSE']._serialized_start=143
  _globals['_GETVIBERESPONSE']._serialized_end=174
  _globals['_VIBESERVICE']._serialized_start=177
  _globals['_VIBESERVICE']._serialized_end=334
# @@protoc_insertion_point(module_scope)
